# Generated by Django 3.2.7 on 2021-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quantity_in_stock', models.DecimalField(decimal_places=1, max_digits=4)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
