# Generated by Django 3.2.7 on 2021-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
