# Generated by Django 3.2.7 on 2021-09-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20210922_0440"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
    ]
